//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_campo_cobertura_control
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public a_campo_cobertura_control()
        {
            this.k_riesgo_residual = new HashSet<k_riesgo_residual>();
            this.k_riesgo_residual1 = new HashSet<k_riesgo_residual>();
            this.k_riesgo_residual2 = new HashSet<k_riesgo_residual>();
            this.k_riesgo_residual3 = new HashSet<k_riesgo_residual>();
            this.k_riesgo_residual4 = new HashSet<k_riesgo_residual>();
            this.k_riesgo_residual5 = new HashSet<k_riesgo_residual>();
            this.k_riesgo_residual6 = new HashSet<k_riesgo_residual>();
            this.k_riesgo_residual7 = new HashSet<k_riesgo_residual>();
            this.k_riesgo_residual8 = new HashSet<k_riesgo_residual>();
            this.k_riesgo_residual9 = new HashSet<k_riesgo_residual>();
            this.k_riesgo_residual10 = new HashSet<k_riesgo_residual>();
            this.k_riesgo_residual11 = new HashSet<k_riesgo_residual>();
            this.k_riesgo_residual12 = new HashSet<k_riesgo_residual>();
            this.k_riesgo_residual13 = new HashSet<k_riesgo_residual>();
        }
    
        public int id_campo_cobertura_control { get; set; }
        public string nb_campo { get; set; }
        public string ds_campo { get; set; }
        public int cl_catalogo { get; set; }
        public int cl_campo { get; set; }
        public int no_orden { get; set; }
        public decimal valor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_riesgo_residual> k_riesgo_residual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_riesgo_residual> k_riesgo_residual1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_riesgo_residual> k_riesgo_residual2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_riesgo_residual> k_riesgo_residual3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_riesgo_residual> k_riesgo_residual4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_riesgo_residual> k_riesgo_residual5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_riesgo_residual> k_riesgo_residual6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_riesgo_residual> k_riesgo_residual7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_riesgo_residual> k_riesgo_residual8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_riesgo_residual> k_riesgo_residual9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_riesgo_residual> k_riesgo_residual10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_riesgo_residual> k_riesgo_residual11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_riesgo_residual> k_riesgo_residual12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_riesgo_residual> k_riesgo_residual13 { get; set; }
    }
}
