//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_input_rc
    {
        public int id_input { get; set; }
        public int id_revision_control { get; set; }
        public Nullable<int> id_calificacion { get; set; }
        public string nb_input { get; set; }
        public string ds_input { get; set; }
        public string tr_input { get; set; }
        public string observaciones { get; set; }
    
        public virtual c_calificacion c_calificacion { get; set; }
        public virtual k_revision_control k_revision_control { get; set; }
    }
}
