//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_area_costeo_sub_proceso
    {
        public int id_sub_proceso { get; set; }
        public int id_area_costeo { get; set; }
        public decimal pr_costeo { get; set; }
    
        public virtual c_area_costeo c_area_costeo { get; set; }
        public virtual c_sub_proceso c_sub_proceso { get; set; }
    }
}
