//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_auditoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public c_auditoria()
        {
            this.c_prueba_auditoria = new HashSet<c_prueba_auditoria>();
            this.c_rango_costeo_auditoria = new HashSet<c_rango_costeo_auditoria>();
            this.k_auditoria = new HashSet<k_auditoria>();
        }
    
        public int id_auditoria { get; set; }
        public int id_entidad { get; set; }
        public int id_area { get; set; }
        public string cl_auditoria { get; set; }
        public string nb_auditoria { get; set; }
        public bool es_regulada { get; set; }
        public int horas_estimadas { get; set; }
        public System.DateTime fe_auditoria { get; set; }
        public System.DateTime fe_ultima_auditoria { get; set; }
        public int id_solicitante_auditoria { get; set; }
        public string sociedades_que_aplica { get; set; }
        public string fundamento_normativo { get; set; }
        public int id_periodo_auditoria { get; set; }
        public int id_mes_entrega { get; set; }
        public string nb_firmante { get; set; }
        public bool presenta_cair { get; set; }
        public bool presenta_comite { get; set; }
        public bool presenta_consejo { get; set; }
        public Nullable<int> id_division_auditoria { get; set; }
        public string cl_color_campo { get; set; }
        public string riesgo { get; set; }
        public Nullable<decimal> cali_audi { get; set; }
    
        public virtual c_area c_area { get; set; }
        public virtual c_entidad c_entidad { get; set; }
        public virtual c_mes c_mes { get; set; }
        public virtual c_periodo_auditoria c_periodo_auditoria { get; set; }
        public virtual c_solicitante_auditoria c_solicitante_auditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_prueba_auditoria> c_prueba_auditoria { get; set; }
        public virtual c_division_auditoria c_division_auditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_rango_costeo_auditoria> c_rango_costeo_auditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_auditoria> k_auditoria { get; set; }
    }
}
