//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using SCIRA.Properties;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class c_campo_programa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public c_campo_programa()
        {
            this.k_campo_programa = new HashSet<k_campo_programa>();
        }
    
        public int id_campo_programa { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [StringLength(128, MinimumLength = 1, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Longitud128")]
        public string cl_campo { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [StringLength(256, MinimumLength = 1, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Longitud256")]
        public string nb_campo { get; set; }
        public string cl_tipo_campo { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(1, 2147483647, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "MCSubProcesoEdit011")]
        public int longitud { get; set; }
        public bool es_editable { get; set; }
        public bool es_requerido { get; set; }
        public string cl_color_borde { get; set; }
        public string cl_color_fondo { get; set; }
        public string msg_ayuda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_campo_programa> k_campo_programa { get; set; }
    }
}
