//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using SCIRA.Properties;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class c_contenido_manual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public c_contenido_manual()
        {
            this.c_contenido_manual1 = new HashSet<c_contenido_manual>();
            this.c_contenido_manual11 = new HashSet<c_contenido_manual>();
            this.c_sub_proceso = new HashSet<c_sub_proceso>();
            this.c_usuario = new HashSet<c_usuario>();
        }

        public int id_contenido_manual { get; set; }
        public Nullable<int> id_contenido_manual_padre { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [StringLength(300, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Longitud300")]
        public string cl_contenido_manual { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public string ds_contenido_manual { get; set; }
        public int id_nivel_manual { get; set; }
        public Nullable<int> no_orden { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_contenido_manual> c_contenido_manual1 { get; set; }
        public virtual c_contenido_manual c_contenido_manual2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_contenido_manual> c_contenido_manual11 { get; set; }
        public virtual c_contenido_manual c_contenido_manual3 { get; set; }
        public virtual c_nivel_manual c_nivel_manual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_sub_proceso> c_sub_proceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_usuario> c_usuario { get; set; }
    }
}
