//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_contenido_normatividad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public c_contenido_normatividad()
        {
            this.c_contenido_normatividad1 = new HashSet<c_contenido_normatividad>();
            this.c_contenido_normatividad11 = new HashSet<c_contenido_normatividad>();
            this.c_sub_proceso_normatividad = new HashSet<c_sub_proceso_normatividad>();
            this.c_area = new HashSet<c_area>();
            this.c_comite = new HashSet<c_comite>();
            this.c_cumplimiento = new HashSet<c_cumplimiento>();
            this.c_frecuencia = new HashSet<c_frecuencia>();
            this.c_obligacion = new HashSet<c_obligacion>();
        }
    
        public int id_contenido_normatividad { get; set; }
        public Nullable<int> id_contenido_normatividad_padre { get; set; }
        public string cl_contenido_normatividad { get; set; }
        public string ds_contenido_normatividad { get; set; }
        public int id_nivel_normatividad { get; set; }
        public bool aparece_en_reporte { get; set; }
        public bool consejo_admo { get; set; }
        public string tema { get; set; }
        public string criticidad1 { get; set; }
        public string monto_multa { get; set; }
        public string plazo_otorgado { get; set; }
        public string requiere_ficha { get; set; }
        public string transitorios { get; set; }
        public string cabildeo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_contenido_normatividad> c_contenido_normatividad1 { get; set; }
        public virtual c_contenido_normatividad c_contenido_normatividad2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_contenido_normatividad> c_contenido_normatividad11 { get; set; }
        public virtual c_contenido_normatividad c_contenido_normatividad3 { get; set; }
        public virtual c_nivel_normatividad c_nivel_normatividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_sub_proceso_normatividad> c_sub_proceso_normatividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_area> c_area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_comite> c_comite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_cumplimiento> c_cumplimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_frecuencia> c_frecuencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_obligacion> c_obligacion { get; set; }

        public int[] id_cumplimiento { get; set; }

        public int[] id_area { get; set; }

        public int[] id_frecuencia { get; set; }
        public int[] id_comite { get; set; }

        public int[] id_obligacion { get; set; }
    }
}
