//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_criticidad
    {
        public int id_probabilidad_ocurrencia { get; set; }
        public int id_magnitud_impacto { get; set; }
        public int id_criticidad_riesgo { get; set; }
    
        public virtual c_criticidad_riesgo c_criticidad_riesgo { get; set; }
        public virtual c_magnitud_impacto c_magnitud_impacto { get; set; }
        public virtual c_probabilidad_ocurrencia c_probabilidad_ocurrencia { get; set; }
    }
}
