//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_criticidad1
    {
        public int id_impacto_monetario { get; set; }
        public int id_factibilidad { get; set; }
        public int id_criticidad_normatividad { get; set; }
    
        public virtual c_criticidad_normatividad c_criticidad_normatividad { get; set; }
        public virtual c_factibilidad c_factibilidad { get; set; }
        public virtual c_impacto_monetario c_impacto_monetario { get; set; }
    }
}
