//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_criticidad_riesgo_ro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public c_criticidad_riesgo_ro()
        {
            this.c_criticidad_ro = new HashSet<c_criticidad_ro>();
        }
    
        public int id_criticidad_riesgo_ro { get; set; }
        public string cl_criticidad_riesgo_ro { get; set; }
        public string nb_criticidad_riesgo_ro { get; set; }
        public string cl_color_campo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_criticidad_ro> c_criticidad_ro { get; set; }
    }
}
