//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using SCIRA.Properties;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class c_indicador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public c_indicador()
        {
            this.k_evaluacion = new HashSet<k_evaluacion>();
        }

        public int id_indicador { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "MacroProcesoCreate003")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "MacroProcesoCreate003")]
        public int id_entidad { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [StringLength(20, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Longitud20")]
        public string cl_indicador { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [StringLength(256, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Longitud256")]
        public string nb_indicador { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [StringLength(512, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "ActividadCosteoIndex002")]
        public string ds_indicador { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [StringLength(512, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "ActividadCosteoIndex002")]
        public string ds_numerador { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [StringLength(512, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "ActividadCosteoIndex002")]
        public string ds_denominador { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate033")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate033")]
        public int id_frecuencia_indicador { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate034")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate034")]
        public Nullable<int> id_unidad_indicador { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate011")]
        [Range((int)1, (int)5, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate030")]
        public decimal peso { get; set; }
        [Range(0, 100, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate013")]
        public decimal umbral000i { get; set; }
        [Range(0, 100, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate014")]
        public decimal umbral000f { get; set; }
        [Range(0, 100, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate016")]
        public decimal umbral050i { get; set; }
        [Range(0, 100, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate017")]
        public decimal umbral050f { get; set; }
        [Range(0, 100, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate019")]
        public decimal umbral075i { get; set; }
        [Range(0, 100, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate020")]
        public decimal umbral075f { get; set; }
        [Range(0, 100, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate022")]
        public decimal umbral100i { get; set; }
        [Range(0, 100, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate023")]
        public decimal umbral100f { get; set; }
        public bool esta_activo { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate035")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate035")]
        public Nullable<int> id_area { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "EntidadCreate005")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "EntidadCreate005")]
        public Nullable<int> id_responsable { get; set; }
        public Nullable<int> id_control { get; set; }

        public virtual c_area c_area { get; set; }
        public virtual c_entidad c_entidad { get; set; }
        public virtual c_frecuencia_indicador c_frecuencia_indicador { get; set; }
        public virtual k_control k_control { get; set; }
        public virtual c_usuario c_usuario { get; set; }
        public virtual c_unidad_indicador c_unidad_indicador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_evaluacion> k_evaluacion { get; set; }
    }
}
