//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using SCIRA.Properties;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class c_indicador_diario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public c_indicador_diario()
        {
            this.k_evaluacion_diaria = new HashSet<k_evaluacion_diaria>();
            this.c_usuario = new HashSet<c_usuario>();
        }
    
        public int id_indicador_diario { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(1,int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public int id_contenido_grupo { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [StringLength(20, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Longitud20")]
        public string cl_indicador_diario { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [StringLength(256, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Longitud256")]
        public string nb_indicador_diario { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [StringLength(512, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate026")]
        public string ds_indicador_diario { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [StringLength(512, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate026")]
        public string ds_numerador_diario { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [StringLength(512, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate026")]
        public string ds_denominador { get; set; }
        public string periodicidad { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(0, 100, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031" +
            "")]
        public decimal umbral000i { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(0, 100, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        public decimal umbral000f { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(0, 100, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        public decimal umbral050i { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(0, 100, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        public decimal umbral050f { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(0, 100, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        public decimal umbral075i { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(0, 100, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        public decimal umbral075f { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(0, 100, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        public decimal umbral100i { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(0, 100, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        public decimal umbral100f { get; set; }
        public bool esta_activo { get; set; }
    
        public virtual c_contenido_grupo c_contenido_grupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_evaluacion_diaria> k_evaluacion_diaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_usuario> c_usuario { get; set; }
    }
}
