//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using SCIRA.Properties;
    using SCIRA.Validaciones;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class c_macro_proceso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public c_macro_proceso()
        {
            this.c_proceso = new HashSet<c_proceso>();
            this.r_macro_proceso = new HashSet<r_macro_proceso>();
            this.k_certificacion_estructura = new HashSet<k_certificacion_estructura>();
        }
    
        public int id_macro_proceso { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "MacroProcesoCreate003")]
        public int id_entidad { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "EntidadCreate003")]
        [StringLength(256, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Longitud50")]
        //[RegularExpression("^((MG)|(MP))([0-9]{1,3})$", ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "MacroProcesoCreate005")]
        [mpCode]
        public string cl_macro_proceso { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "EntidadCreate004")]
        [StringLength(256, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "SubEtapaCreate002")]
        public string nb_macro_proceso { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "EntidadCreate005")]
        public int id_responsable { get; set; }
    
        public virtual c_entidad c_entidad { get; set; }
        public virtual c_usuario c_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_proceso> c_proceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<r_macro_proceso> r_macro_proceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_certificacion_estructura> k_certificacion_estructura { get; set; }
    }
}
