//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using SCIRA.Properties;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class c_meta_campo
    {
        public int id_meta_campo { get; set; }
        public string nb_entidad { get; set; }
        public string cl_campo { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [StringLength(256, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Longitud256")]
        public string nb_campo { get; set; }
        public string cl_tipo_campo { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(1, 2147483647, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "MCSubProcesoEdit011")]
        public int longitud_campo { get; set; }
        public bool aparece_en_mg { get; set; }
        public bool es_visible { get; set; }
        public bool es_editable { get; set; }
        public bool es_requerido { get; set; }
        public string cl_color_borde { get; set; }
        public string cl_color_fondo { get; set; }
        public string msg_ayuda { get; set; }
    }
}
