//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using SCIRA.Properties;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class c_normatividad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public c_normatividad()
        {
            this.c_nivel_normatividad = new HashSet<c_nivel_normatividad>();
        }

        public int id_normatividad { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [StringLength(20, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Longitud20")]
        public string cl_normatividad { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [StringLength(256, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Longitud256")]
        public string nb_normatividad { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [StringLength(512, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate026")]
        public string ds_normatividad { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "NormatividadCreate011")]
        public Nullable<System.DateTime> fe_publicacion_dof { get; set; }
        [StringLength(512, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate026")]
        public string ds_sectores { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "NormatividadCreate038")]
        public Nullable<int> id_tipo_normatividad { get; set; }
        public Nullable<int> id_root_contenido { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_nivel_normatividad> c_nivel_normatividad { get; set; }
        public virtual c_tipo_normatividad c_tipo_normatividad { get; set; }
    }
}
