//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_puesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public c_puesto()
        {
            this.c_puesto1 = new HashSet<c_puesto>();
            this.c_puesto11 = new HashSet<c_puesto>();
            this.c_usuario = new HashSet<c_usuario>();
        }
    
        public int id_puesto { get; set; }
        public Nullable<int> id_puesto_padre { get; set; }
        public string cl_puesto { get; set; }
        public string nb_puesto { get; set; }
        public Nullable<bool> se_notifica { get; set; }
        public string tag_puesto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_puesto> c_puesto1 { get; set; }
        public virtual c_puesto c_puesto2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_puesto> c_puesto11 { get; set; }
        public virtual c_puesto c_puesto3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_usuario> c_usuario { get; set; }
    }
}
