//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_rango
    {
        public int id_rango { get; set; }
        public string cl_rango { get; set; }
        public string nb_rango { get; set; }
        public string cl_color_campo { get; set; }
        public string valor { get; set; }
        public string segmentacion_calificacion { get; set; }
        public string segmentacion_calificacion2 { get; set; }
    }
}
