//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_rango_costeo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public c_rango_costeo()
        {
            this.c_rango_costeo_auditoria = new HashSet<c_rango_costeo_auditoria>();
        }
    
        public int id_rango_costeo { get; set; }
        public string cl_rango_costeo { get; set; }
        public string nb_rango_costeo { get; set; }
        public decimal pr_costeo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_rango_costeo_auditoria> c_rango_costeo_auditoria { get; set; }
    }
}
