//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_rango_costeo_auditoria
    {
        public int id_auditoria { get; set; }
        public int id_rango_costeo { get; set; }
        public decimal pr_costeo { get; set; }
        public Nullable<int> id_rango { get; set; }
    
        public virtual c_auditoria c_auditoria { get; set; }
        public virtual c_rango_costeo c_rango_costeo { get; set; }
    }
}
