//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_reporte_regulatorio
    {
        public int id_reporte_regulatorio { get; set; }
        public string cl_reporte_regulatorio { get; set; }
        public int nb_reporte_regulatorio { get; set; }
    }
}
