//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_sub_proceso_normatividad
    {
        public int id_sub_proceso { get; set; }
        public int id_contenido_normatividad { get; set; }
        public bool es_raiz { get; set; }
    
        public virtual c_contenido_normatividad c_contenido_normatividad { get; set; }
        public virtual c_sub_proceso c_sub_proceso { get; set; }
    }
}
