//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using SCIRA.Properties;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class k_bdei
    {
        //Datos Generales
        public int id_bdei { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public int id_entidad { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public int id_estatus_bdei { get; set; }
        public Nullable<int> id_sub_proceso { get; set; }
        public Nullable<int> id_responsable_captura { get; set; }
		
		
		//Datos del Evento
        public Nullable<System.DateTime> fe_alta { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public Nullable<System.DateTime> fe_ocurrencia { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public string hr_ocurrencia { get; set; }
        [Range(0, 32767, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion002")]
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public Nullable<short> duracion { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public Nullable<System.DateTime> fe_solucion { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public Nullable<int> id_tipo_solucion { get; set; }
        [MaxLength(4000, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Longitud4000")]
        public string comentarios { get; set; }
		
		[Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        public Nullable<int> id_clase_evento { get; set; }
		[Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public Nullable<int> id_proceso_riesgo_operacional { get; set; }
		[Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public Nullable<int> id_sub_tipo_producto_riesgo_operacional { get; set; }
		[Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public Nullable<int> id_canal_riesgo_operacional { get; set; }
		[Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public Nullable<int> id_linea_negocio_riesgo_operacional { get; set; }
		[Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public Nullable<int> id_frecuencia_riesgo_operacional { get; set; }
		[Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public Nullable<int> id_impacto_riesgo_operacional { get; set; }
		
		
		
        //Datos de la Pérdida
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public Nullable<int> id_moneda { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public Nullable<int> id_cuenta_contable_perdida { get; set; }
        [Range(0, 9999999999, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        public Nullable<decimal> mn_exposicion { get; set; }
        [Range(0, 9999999999, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        public Nullable<decimal> mn_quebranto { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public Nullable<int> id_centro_costo { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public Nullable<System.DateTime> fe_registro_perdida { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public Nullable<System.DateTime> fe_quebranto { get; set; }
		
		
        //Datos de la Recuperación
        [Range(0, 9999999999, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        public Nullable<decimal> mn_recuperacion { get; set; }
        public Nullable<int> id_responsable_recuperacion { get; set; }
        public Nullable<int> id_cuenta_contable_recuperacion { get; set; }
        public Nullable<System.DateTime> fe_registro_recuperacion { get; set; }
        [StringLength(256, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Longitud256")]
        public string via_recuperacion { get; set; }
        [Range(0, 9999999999, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        public Nullable<decimal> mn_costo_recuperacion { get; set; }
        public Nullable<int> id_cuenta_contable_costo { get; set; }
        public Nullable<System.DateTime> fe_registro_costo_recuperacion { get; set; }
		
		
		
		//Datos nuevos r28
        public Nullable<int> id_ds_evento { get; set; }
        public Nullable<int> id_tipo_riesgo_asociado { get; set; }
        public Nullable<int> id_concepto_cuenta_contable { get; set; }
        public Nullable<int> id_cuenta_contable_metodo_estandar { get; set; }
        public Nullable<decimal> mn_perdida_actualizado { get; set; }
        public Nullable<System.DateTime> fe_modificación_monto_perdida { get; set; }

        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(0, 9999999999, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        public Nullable<int> no_procesos_afectados { get; set; }

        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(0, 9999999999, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        public Nullable<int> no_productos_afectados { get; set; }

        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(0, 9999999999, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        public Nullable<int> no_lineas_negocio_afectadas { get; set; }

        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public Nullable<System.DateTime> fe_ocurrencia_manual { get; set; }
        public Nullable<System.DateTime> fe_modificacion_monto_perdida { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(0, 9999999999, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        public string no_evento_sencillo { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(0, 9999999999, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        public string no_evento_multiple { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(0, 9999999999, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        public string folio_riesgo_operacional { get; set; }

        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        public Nullable<int> id_causa_bdei { get; set; }

        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public Nullable<int> id_riesgo_asociado_bdei { get; set; }

        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public int id_catalogo_concepto { get; set; }
        public Nullable<int> id_minimo_riesgo_operativo { get; set; }
		
		
		//En desuso
        public Nullable<int> id_causa_riesgo_operacional { get; set; }
		
    
        public virtual c_canal_riesgo_operacional c_canal_riesgo_operacional { get; set; }
        public virtual c_catalogo_concepto c_catalogo_concepto { get; set; }
        public virtual c_causa_bdei c_causa_bdei { get; set; }
        public virtual c_centro_costo c_centro_costo { get; set; }
        public virtual c_clase_evento c_clase_evento { get; set; }
        public virtual c_concepto_cuenta_contable c_concepto_cuenta_contable { get; set; }
        public virtual c_cuenta_contable c_cuenta_contable { get; set; }
        public virtual c_cuenta_contable c_cuenta_contable1 { get; set; }
        public virtual c_cuenta_contable c_cuenta_contable2 { get; set; }
        public virtual c_cuenta_contable c_cuenta_contable3 { get; set; }
        public virtual c_ds_evento c_ds_evento { get; set; }
        public virtual c_entidad c_entidad { get; set; }
        public virtual c_estatus_bdei c_estatus_bdei { get; set; }
        public virtual c_frecuencia_riesgo_operacional c_frecuencia_riesgo_operacional { get; set; }
        public virtual c_impacto_riesgo_operacional c_impacto_riesgo_operacional { get; set; }
        public virtual c_linea_negocio_riesgo_operacional c_linea_negocio_riesgo_operacional { get; set; }
        public virtual c_minimo_riesgo_operativo c_minimo_riesgo_operativo { get; set; }
        public virtual c_moneda c_moneda { get; set; }
        public virtual c_proceso_riesgo_operacional c_proceso_riesgo_operacional { get; set; }
        public virtual c_riesgo_asociado_bdei c_riesgo_asociado_bdei { get; set; }
        public virtual c_sub_proceso c_sub_proceso { get; set; }
        public virtual c_sub_tipo_producto_riesgo_operacional c_sub_tipo_producto_riesgo_operacional { get; set; }
        public virtual c_tipo_riesgo_asociado c_tipo_riesgo_asociado { get; set; }
        public virtual c_tipo_solucion c_tipo_solucion { get; set; }
        public virtual c_usuario c_usuario { get; set; }
        public virtual c_usuario c_usuario1 { get; set; }
    }
}
