//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class k_campo_programa
    {
        public int idd_campo_programa { get; set; }
        public int idd_programa_trabajo { get; set; }
        public int id_campo_programa { get; set; }
        public string valor { get; set; }
        public bool aplica { get; set; }
    
        public virtual c_campo_programa c_campo_programa { get; set; }
        public virtual k_programa_trabajo k_programa_trabajo { get; set; }
    }
}
