//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using SCIRA.Properties;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class k_certificacion_estructura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public k_certificacion_estructura()
        {
            this.c_archivo = new HashSet<c_archivo>();
        }
    
        public int id_certificacion_estructura { get; set; }
        public string cl_certificacion_estructura { get; set; }
        public int id_periodo_certificacion { get; set; }
        public Nullable<int> id_sub_proceso { get; set; }
        public Nullable<int> id_proceso { get; set; }
        public Nullable<int> id_macro_proceso { get; set; }
        public Nullable<int> id_entidad { get; set; }
        public string leyenda_certificacion_estructura { get; set; }
        public bool resultado { get; set; }
        [MaxLength(512, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "ActividadCosteoIndex002")]
        public string comentarios { get; set; }
    
        public virtual c_entidad c_entidad { get; set; }
        public virtual c_macro_proceso c_macro_proceso { get; set; }
        public virtual c_periodo_certificacion c_periodo_certificacion { get; set; }
        public virtual c_proceso c_proceso { get; set; }
        public virtual c_sub_proceso c_sub_proceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_archivo> c_archivo { get; set; }
    }
}
