//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using SCIRA.Properties;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class k_comentario_programa_trabajo
    {
        public int id_comentario_programa_trabajo { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public string comentario { get; set; }
        public System.DateTime fe_comentario { get; set; }
        public string nb_responsable { get; set; }
        public int idd_programa_trabajo { get; set; }
    
        public virtual k_programa_trabajo k_programa_trabajo { get; set; }
    }
}
