//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class k_control
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public k_control()
        {
            this.c_indicador = new HashSet<c_indicador>();
            this.k_certificacion_control = new HashSet<k_certificacion_control>();
            this.k_incidencia = new HashSet<k_incidencia>();
            this.k_revision_control = new HashSet<k_revision_control>();
            this.k_riesgo_residual = new HashSet<k_riesgo_residual>();
            this.r_control = new HashSet<r_control>();
            this.c_aseveracion = new HashSet<c_aseveracion>();
            this.c_archivo = new HashSet<c_archivo>();
            this.k_riesgo = new HashSet<k_riesgo>();
        }
    
        public int id_control { get; set; }
        public int id_sub_proceso { get; set; }
        public string actividad_control { get; set; }
        public string relacion_control { get; set; }
        public string evidencia_control { get; set; }
        public Nullable<int> id_ejecutor { get; set; }
        public Nullable<int> id_responsable { get; set; }
        public bool es_control_clave { get; set; }
        public Nullable<int> id_grado_cobertura { get; set; }
        public Nullable<int> id_frecuencia_control { get; set; }
        public Nullable<int> id_naturaleza_control { get; set; }
        public string nb_aplicacion { get; set; }
        public Nullable<int> id_tipologia_control { get; set; }
        public Nullable<int> id_categoria_control { get; set; }
        public Nullable<int> id_tipo_evidencia { get; set; }
        public bool tiene_accion_correctora { get; set; }
        public string accion_correctora { get; set; }
        public string ds_notificacion_incidencia { get; set; }
        public string campo01 { get; set; }
        public string campo02 { get; set; }
        public string campo03 { get; set; }
        public string campo04 { get; set; }
        public string campo05 { get; set; }
        public string campo06 { get; set; }
        public string campo07 { get; set; }
        public string campo08 { get; set; }
        public string campo09 { get; set; }
        public string campo10 { get; set; }
        public string campo11 { get; set; }
        public string campo12 { get; set; }
        public string campo13 { get; set; }
        public string campo14 { get; set; }
        public string campo15 { get; set; }
        public string campo16 { get; set; }
        public string campo17 { get; set; }
        public string campo18 { get; set; }
        public string campo19 { get; set; }
        public string campo20 { get; set; }
    
        public virtual c_categoria_control c_categoria_control { get; set; }
        public virtual c_frecuencia_control c_frecuencia_control { get; set; }
        public virtual c_grado_cobertura c_grado_cobertura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_indicador> c_indicador { get; set; }
        public virtual c_naturaleza_control c_naturaleza_control { get; set; }
        public virtual c_sub_proceso c_sub_proceso { get; set; }
        public virtual c_tipo_evidencia c_tipo_evidencia { get; set; }
        public virtual c_tipologia_control c_tipologia_control { get; set; }
        public virtual c_usuario c_usuario { get; set; }
        public virtual c_usuario c_usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_certificacion_control> k_certificacion_control { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_incidencia> k_incidencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_revision_control> k_revision_control { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_riesgo_residual> k_riesgo_residual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<r_control> r_control { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_aseveracion> c_aseveracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_archivo> c_archivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_riesgo> k_riesgo { get; set; }
    }
}
