//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using SCIRA.Properties;
    using SCIRA.Validaciones;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class k_evaluacion
    {
        public int id_evaluacion { get; set; }
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "EvaluacionIndicadorCreate009")]
        public Nullable<int> id_indicador { get; set; }
        public int id_periodo_indicador { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(0, 999999999999999999, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        public decimal numerador { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [CompararNumerador]
        [Range(0, 999999999999999999, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "IndicadorCreate031")]
        public decimal denominador { get; set; }
        public decimal medicion { get; set; }
        public Nullable<int> id_calificacion_indicador { get; set; }

        public virtual c_calificacion_indicador c_calificacion_indicador { get; set; }
        public virtual c_indicador c_indicador { get; set; }
        public virtual c_periodo_indicador c_periodo_indicador { get; set; }
    }
}
