//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class k_evaluacion_diaria
    {
        public int id_evaluacion_diaria { get; set; }
        public int id_indicador_diario { get; set; }
        public int id_contenido_grupo { get; set; }
        public int id_usuario { get; set; }
        public Nullable<decimal> numerador { get; set; }
        public Nullable<decimal> denominador { get; set; }
        public Nullable<System.DateTime> fe_evaluacion { get; set; }
    
        public virtual c_contenido_grupo c_contenido_grupo { get; set; }
        public virtual c_indicador_diario c_indicador_diario { get; set; }
        public virtual c_usuario c_usuario { get; set; }
    }
}
