//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using SCIRA.Properties;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class k_incidencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public k_incidencia()
        {
            this.k_plan = new HashSet<k_plan>();
            this.r_respuesta = new HashSet<r_respuesta>();
        }
    
	
	
		public int id_incidencia { get; set; }
        public Nullable<int> id_objeto { get; set; }
        public Nullable<int> id_certificacion_control { get; set; }
        public Nullable<int> id_control { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(1,int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public int id_responsable { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public int id_clasificacion_incidencia { get; set; }
        [StringLength(20, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Longitud20")]
        public string lvl_1 { get; set; }
        [StringLength(20, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Longitud20")]
        public string lvl_2 { get; set; }
        [StringLength(20, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Longitud20")]
        public string lvl_3 { get; set; }
        [StringLength(20, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Longitud20")]
        public string lvl_4 { get; set; }
        [StringLength(20, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Longitud20")]
        public string lvl_5 { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public string ds_incidencia { get; set; }
        public string js_incidencia { get; set; }
        public string archivo_1 { get; set; }
        public string archivo_2 { get; set; }
        public bool requiere_plan { get; set; }
    
        public virtual c_clasificacion_incidencia c_clasificacion_incidencia { get; set; }
        public virtual c_usuario c_usuario { get; set; }
        public virtual k_certificacion_control k_certificacion_control { get; set; }
        public virtual k_control k_control { get; set; }
        public virtual k_objeto k_objeto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_plan> k_plan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<r_respuesta> r_respuesta { get; set; }
    }
}
