//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using SCIRA.Properties;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
	
    public partial class k_objeto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public k_objeto()
        {
            this.k_incidencia = new HashSet<k_incidencia>();
            this.r_contestacion_oficio = new HashSet<r_contestacion_oficio>();
            this.k_objeto1 = new HashSet<k_objeto>();
            this.k_objeto2 = new HashSet<k_objeto>();
        }
    
        public int id_objeto { get; set; }
		[Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [Range(1,int.MaxValue, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public int id_entidad { get; set; }
        public Nullable<int> id_responsable { get; set; }
        public Nullable<int> id_autoridad { get; set; }
        public Nullable<int> no_incidencias { get; set; }
        public int tipo_objeto { get; set; }
        public Nullable<System.DateTime> fe_alta { get; set; }
        public Nullable<System.DateTime> fe_vencimiento { get; set; }
        public Nullable<System.DateTime> fe_contestacion { get; set; }
		[Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        [StringLength(256, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Longitud256")]
        public string nb_objeto { get; set; }
        public string ds_objeto { get; set; }
        public string nb_archivo_1 { get; set; }
		public string nb_archivo_2 { get; set; }
	
        public virtual c_entidad c_entidad { get; set; }
        public virtual c_origen_autoridad c_origen_autoridad { get; set; }
        public virtual c_usuario c_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_incidencia> k_incidencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<r_contestacion_oficio> r_contestacion_oficio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_objeto> k_objeto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_objeto> k_objeto2 { get; set; }
    }
}
