//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class k_programa_trabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public k_programa_trabajo()
        {
            this.k_campo_programa = new HashSet<k_campo_programa>();
            this.k_comentario_programa_trabajo = new HashSet<k_comentario_programa_trabajo>();
            this.c_archivo = new HashSet<c_archivo>();
            this.c_archivo1 = new HashSet<c_archivo>();
        }
    
        public int idd_programa_trabajo { get; set; }
        public int id_prueba_auditoria { get; set; }
        public string resultado { get; set; }
        public int idd_auditoria { get; set; }
        public bool esta_atendida { get; set; }
        public string comentarios { get; set; }
        public bool tiene_incidencia { get; set; }
        public string incidencia_detectada { get; set; }
        public string recomendaciones { get; set; }
        public Nullable<int> id_criticidad_programa_trabajo { get; set; }
        public string tema { get; set; }
        public Nullable<System.DateTime> fe_resolucion { get; set; }
        public string responsable { get; set; }
        public Nullable<int> id_estatus_programa_trabajo { get; set; }
        public bool es_duplicada { get; set; }
    
        public virtual c_criticidad_programa_trabajo c_criticidad_programa_trabajo { get; set; }
        public virtual c_estatus_programa_trabajo c_estatus_programa_trabajo { get; set; }
        public virtual c_prueba_auditoria c_prueba_auditoria { get; set; }
        public virtual k_auditoria k_auditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_campo_programa> k_campo_programa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_comentario_programa_trabajo> k_comentario_programa_trabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_archivo> c_archivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_archivo> c_archivo1 { get; set; }
    }
}
