//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class k_revision_control
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public k_revision_control()
        {
            this.a_input_rc = new HashSet<a_input_rc>();
            this.a_procedimiento_prueba_rc = new HashSet<a_procedimiento_prueba_rc>();
            this.c_aseveracion = new HashSet<c_aseveracion>();
            this.c_archivo = new HashSet<c_archivo>();
        }
    
        public int id_revision_control { get; set; }
        public int id_control { get; set; }
        public Nullable<int> id_tipologia_control_rc { get; set; }
        public Nullable<int> id_frecuencia_control_rc { get; set; }
        public Nullable<int> id_naturaleza_control_edc { get; set; }
        public Nullable<int> id_tipologia_control_edc { get; set; }
        public Nullable<int> id_tipo_evidencia_control_edc { get; set; }
        public Nullable<int> id_categoría_control_edc { get; set; }
        public string dg_entidad { get; set; }
        public string dg_marco_proceso { get; set; }
        public string dg_proceso { get; set; }
        public string dg_sub_proceso { get; set; }
        public string dg_tarea { get; set; }
        public Nullable<System.DateTime> dg_fe_revision { get; set; }
        public string dg_nb_responsable_revision { get; set; }
        public string rr_evento_riesgo { get; set; }
        public string rr_magnitud_impacto { get; set; }
        public string rr_probabilidad_ocurrencia { get; set; }
        public string rc_codigo_manual { get; set; }
        public string rc_actividad_control { get; set; }
        public string rc_evidencia_control { get; set; }
        public string rc_ds_control { get; set; }
        public string rc_dir_general { get; set; }
        public string rc_area { get; set; }
        public string rc_responsable { get; set; }
        public string rc_puesto_responsable { get; set; }
        public string rc_ejecutor { get; set; }
        public string rc_puesto_ejecutor { get; set; }
        public bool rc_control_clave { get; set; }
        public bool rc_control_dependiente { get; set; }
        public string edc_informacion_inputs { get; set; }
        public string edc_informacion_ouputs { get; set; }
        public string edc_tr_ouputs { get; set; }
        public string edc_proc_cert { get; set; }
        public string edc_fc1 { get; set; }
        public string edc_fc2 { get; set; }
        public string edc_fc3 { get; set; }
        public string edc_fc4 { get; set; }
        public string edc_fc5 { get; set; }
        public bool edc_diseño_efectivo { get; set; }
        public string edc_efectividad { get; set; }
        public bool eeo_diseño_efectivo { get; set; }
        public string eeo_efectividad { get; set; }
        public string cg_conclusion { get; set; }
        public string cg_comentarios_revision { get; set; }
        public Nullable<int> cg_calificacion { get; set; }
        public Nullable<int> id_cc1 { get; set; }
        public Nullable<int> id_cc2 { get; set; }
        public Nullable<int> id_cc3 { get; set; }
        public Nullable<int> id_cc4 { get; set; }
        public Nullable<int> id_cc5 { get; set; }
        public Nullable<int> id_cc6 { get; set; }
        public Nullable<int> id_cc7 { get; set; }
        public Nullable<int> id_cc8 { get; set; }
        public Nullable<int> id_cc9 { get; set; }
        public Nullable<int> id_cc10 { get; set; }
        public Nullable<int> id_cc11 { get; set; }
        public Nullable<int> id_cc12 { get; set; }
        public Nullable<int> id_cc13 { get; set; }
        public Nullable<int> id_cc14 { get; set; }
        public Nullable<int> id_cc15 { get; set; }
        public Nullable<int> id_cc16 { get; set; }
        public Nullable<int> id_cc17 { get; set; }
        public Nullable<int> id_cc18 { get; set; }
        public Nullable<int> id_cc19 { get; set; }
        public Nullable<int> id_cc20 { get; set; }
        public Nullable<int> id_cc21 { get; set; }
        public Nullable<int> id_cc22 { get; set; }
        public Nullable<int> id_cc23 { get; set; }
        public Nullable<int> id_cc24 { get; set; }
        public Nullable<int> id_cc25 { get; set; }
        public Nullable<int> id_cc26 { get; set; }
        public Nullable<int> id_cc27 { get; set; }
        public Nullable<int> id_cc28 { get; set; }
        public Nullable<int> id_cc29 { get; set; }
        public Nullable<int> id_cc30 { get; set; }
        public Nullable<int> id_cc31 { get; set; }
        public Nullable<int> id_cc32 { get; set; }
        public Nullable<int> id_cc33 { get; set; }
        public Nullable<int> id_cc34 { get; set; }
        public Nullable<int> id_cc35 { get; set; }
        public Nullable<int> id_cc36 { get; set; }
        public Nullable<int> id_cc37 { get; set; }
        public Nullable<int> id_cc38 { get; set; }
        public Nullable<int> id_cc39 { get; set; }
        public Nullable<int> id_cc40 { get; set; }
        public Nullable<int> id_cc41 { get; set; }
        public string dg_obs_1 { get; set; }
        public string dg_obs_2 { get; set; }
        public string dg_obs_3 { get; set; }
        public string dg_obs_4 { get; set; }
        public string dg_obs_5 { get; set; }
        public string rr_obs_1 { get; set; }
        public string rr_obs_2 { get; set; }
        public string rr_obs_3 { get; set; }
        public string rc_obs_1 { get; set; }
        public string rc_obs_2 { get; set; }
        public string rc_obs_3 { get; set; }
        public string rc_obs_4 { get; set; }
        public string rc_obs_5 { get; set; }
        public string rc_obs_6 { get; set; }
        public string rc_obs_7 { get; set; }
        public string rc_obs_8 { get; set; }
        public string rc_obs_9 { get; set; }
        public string rc_obs_10 { get; set; }
        public string rc_obs_11 { get; set; }
        public string rc_obs_12 { get; set; }
        public string rc_obs_13 { get; set; }
        public string rc_obs_14 { get; set; }
        public string rc_obs_15 { get; set; }
        public string edc_obs_1 { get; set; }
        public string edc_obs_2 { get; set; }
        public string edc_obs_3 { get; set; }
        public string edc_obs_4 { get; set; }
        public string edc_obs_5 { get; set; }
        public string edc_obs_6 { get; set; }
        public string edc_obs_7 { get; set; }
        public string edc_obs_8 { get; set; }
        public string edc_obs_9 { get; set; }
        public string edc_obs_10 { get; set; }
        public string edc_obs_11 { get; set; }
        public string edc_obs_12 { get; set; }
        public string edc_obs_13 { get; set; }
        public string eeo_obs_1 { get; set; }
        public string eeo_obs_2 { get; set; }
        public string cg_obs_1 { get; set; }
        public Nullable<int> id_calificacion_revision { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<a_input_rc> a_input_rc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<a_procedimiento_prueba_rc> a_procedimiento_prueba_rc { get; set; }
        public virtual c_calificacion c_calificacion { get; set; }
        public virtual c_calificacion c_calificacion1 { get; set; }
        public virtual c_calificacion c_calificacion2 { get; set; }
        public virtual c_calificacion c_calificacion3 { get; set; }
        public virtual c_calificacion c_calificacion4 { get; set; }
        public virtual c_calificacion c_calificacion5 { get; set; }
        public virtual c_calificacion c_calificacion6 { get; set; }
        public virtual c_calificacion c_calificacion7 { get; set; }
        public virtual c_calificacion c_calificacion8 { get; set; }
        public virtual c_calificacion c_calificacion9 { get; set; }
        public virtual c_calificacion c_calificacion10 { get; set; }
        public virtual c_calificacion c_calificacion11 { get; set; }
        public virtual c_calificacion c_calificacion12 { get; set; }
        public virtual c_calificacion c_calificacion13 { get; set; }
        public virtual c_calificacion c_calificacion14 { get; set; }
        public virtual c_calificacion c_calificacion15 { get; set; }
        public virtual c_calificacion c_calificacion16 { get; set; }
        public virtual c_calificacion c_calificacion17 { get; set; }
        public virtual c_calificacion c_calificacion18 { get; set; }
        public virtual c_calificacion c_calificacion19 { get; set; }
        public virtual c_calificacion c_calificacion20 { get; set; }
        public virtual c_calificacion c_calificacion21 { get; set; }
        public virtual c_calificacion c_calificacion22 { get; set; }
        public virtual c_calificacion c_calificacion23 { get; set; }
        public virtual c_calificacion c_calificacion24 { get; set; }
        public virtual c_calificacion c_calificacion25 { get; set; }
        public virtual c_calificacion c_calificacion26 { get; set; }
        public virtual c_calificacion c_calificacion27 { get; set; }
        public virtual c_calificacion c_calificacion28 { get; set; }
        public virtual c_calificacion c_calificacion29 { get; set; }
        public virtual c_calificacion c_calificacion30 { get; set; }
        public virtual c_calificacion c_calificacion31 { get; set; }
        public virtual c_calificacion c_calificacion32 { get; set; }
        public virtual c_calificacion c_calificacion33 { get; set; }
        public virtual c_calificacion c_calificacion34 { get; set; }
        public virtual c_calificacion c_calificacion35 { get; set; }
        public virtual c_calificacion c_calificacion36 { get; set; }
        public virtual c_calificacion c_calificacion37 { get; set; }
        public virtual c_calificacion c_calificacion38 { get; set; }
        public virtual c_calificacion c_calificacion39 { get; set; }
        public virtual c_calificacion c_calificacion40 { get; set; }
        public virtual c_calificacion_revision c_calificacion_revision { get; set; }
        public virtual c_categoria_control c_categoria_control { get; set; }
        public virtual c_frecuencia_control c_frecuencia_control { get; set; }
        public virtual c_naturaleza_control c_naturaleza_control { get; set; }
        public virtual c_tipo_evidencia c_tipo_evidencia { get; set; }
        public virtual c_tipologia_control c_tipologia_control { get; set; }
        public virtual c_tipologia_control c_tipologia_control1 { get; set; }
        public virtual k_control k_control { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_aseveracion> c_aseveracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_archivo> c_archivo { get; set; }
    }
}
