//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using SCIRA.Properties;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class k_riesgo_derogado
    {
        public int id_riesgo_derogado { get; set; }
        public int id_sub_proceso { get; set; }
        public string evento { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "RiesgoDelete003")]
        public string justificacion { get; set; }
        public string cl_riesgo { get; set; }
        public string nb_riesgo { get; set; }
        public string tipo_riesgo { get; set; }
        public string tipologia_riesgo { get; set; }
        public string probabilidad_ocurrencia { get; set; }
        public string tipo_impacto { get; set; }
        public string magnitud_impacto { get; set; }
        public string criticidad { get; set; }
        public bool tiene_afectacion_contable { get; set; }
        public string supuesto_normativo { get; set; }
        public string euc { get; set; }
        public string campo01 { get; set; }
        public string campo02 { get; set; }
        public string campo03 { get; set; }
        public string campo04 { get; set; }
        public string campo05 { get; set; }
        public string campo06 { get; set; }
        public string campo07 { get; set; }
        public string campo08 { get; set; }
        public string campo09 { get; set; }
        public string campo10 { get; set; }
        public string campo11 { get; set; }
        public string campo12 { get; set; }
        public string campo13 { get; set; }
        public string campo14 { get; set; }
        public string campo15 { get; set; }
        public string campo16 { get; set; }
        public string campo17 { get; set; }
        public string campo18 { get; set; }
        public string campo19 { get; set; }
        public string campo20 { get; set; }
        public bool es_riesgo_operativo { get; set; }
        public string proceso_riesgo_operacional { get; set; }
        public string sub_tipo_producto_riesgo_operacional { get; set; }
        public string sub_tipo_riesgo_operacional { get; set; }
        public string linea_negocio_riesgo_operacional { get; set; }
        public string frecuencia_riesgo_operacional { get; set; }
        public string impacto_riesgo_operacional { get; set; }
        public string criticidadRO { get; set; }
    
        public virtual c_sub_proceso c_sub_proceso { get; set; }
    }
}
