//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class k_riesgo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public k_riesgo()
        {
            this.r_riesgo = new HashSet<r_riesgo>();
            this.k_control = new HashSet<k_control>();
            this.c_error_contable = new HashSet<c_error_contable>();
        }
    
        public int id_riesgo { get; set; }
        public int id_sub_proceso { get; set; }
        public string cl_riesgo { get; set; }
        public string nb_riesgo { get; set; }
        public string evento { get; set; }
        public Nullable<int> id_tipo_riesgo { get; set; }
        public Nullable<int> id_tipologia_riesgo { get; set; }
        public Nullable<int> id_probabilidad_ocurrencia { get; set; }
        public Nullable<int> id_tipo_impacto { get; set; }
        public Nullable<int> id_magnitud_impacto { get; set; }
        public string criticidad { get; set; }
        public bool tiene_afectacion_contable { get; set; }
        public string supuesto_normativo { get; set; }
        public string euc { get; set; }
        public string campo01 { get; set; }
        public string campo02 { get; set; }
        public string campo03 { get; set; }
        public string campo04 { get; set; }
        public string campo05 { get; set; }
        public string campo06 { get; set; }
        public string campo07 { get; set; }
        public string campo08 { get; set; }
        public string campo09 { get; set; }
        public string campo10 { get; set; }
        public string campo11 { get; set; }
        public string campo12 { get; set; }
        public string campo13 { get; set; }
        public string campo14 { get; set; }
        public string campo15 { get; set; }
        public string campo16 { get; set; }
        public string campo17 { get; set; }
        public string campo18 { get; set; }
        public string campo19 { get; set; }
        public string campo20 { get; set; }
        public bool es_riesgo_operativo { get; set; }
        public Nullable<int> id_proceso_riesgo_operacional { get; set; }
        public Nullable<int> id_sub_tipo_riesgo_operacional { get; set; }
        public Nullable<int> id_linea_negocio_riesgo_operacional { get; set; }
        public Nullable<int> id_frecuencia_riesgo_operacional { get; set; }
        public Nullable<int> id_impacto_riesgo_operacional { get; set; }
        public Nullable<int> id_sub_tipo_producto_riesgo_operacional { get; set; }
    
        public virtual c_frecuencia_riesgo_operacional c_frecuencia_riesgo_operacional { get; set; }
        public virtual c_impacto_riesgo_operacional c_impacto_riesgo_operacional { get; set; }
        public virtual c_linea_negocio_riesgo_operacional c_linea_negocio_riesgo_operacional { get; set; }
        public virtual c_magnitud_impacto c_magnitud_impacto { get; set; }
        public virtual c_probabilidad_ocurrencia c_probabilidad_ocurrencia { get; set; }
        public virtual c_proceso_riesgo_operacional c_proceso_riesgo_operacional { get; set; }
        public virtual c_sub_proceso c_sub_proceso { get; set; }
        public virtual c_sub_tipo_producto_riesgo_operacional c_sub_tipo_producto_riesgo_operacional { get; set; }
        public virtual c_sub_tipo_riesgo_operacional c_sub_tipo_riesgo_operacional { get; set; }
        public virtual c_tipo_impacto c_tipo_impacto { get; set; }
        public virtual c_tipo_riesgo c_tipo_riesgo { get; set; }
        public virtual c_tipologia_riesgo c_tipologia_riesgo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<r_riesgo> r_riesgo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<k_control> k_control { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_error_contable> c_error_contable { get; set; }
    }
}
