//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class k_riesgo_residual
    {
        public int id_riesgo_residual { get; set; }
        public int id_control { get; set; }
        public int dc_ejecucion_sistematica { get; set; }
        public int dc_pistas_auditoria { get; set; }
        public int dc_cumplimiento_politicas_entidad { get; set; }
        public int dc_umbrales_adecuados_indicadores { get; set; }
        public int dc_metodologia_reporte { get; set; }
        public int dc_evaluacion_diseño { get; set; }
        public int dc_responsable_diseño { get; set; }
        public int dc_entrada_datos { get; set; }
        public int dc_resultado_sin_manipulacion { get; set; }
        public int ec_planes_remediacion { get; set; }
        public int ec_eventos_relacionados { get; set; }
        public int ec_evaluacion_efectividad { get; set; }
        public int ec_efectividad_indicadores { get; set; }
        public int ec_tiempo_madurez_control { get; set; }
    
        public virtual a_campo_cobertura_control a_campo_cobertura_control { get; set; }
        public virtual a_campo_cobertura_control a_campo_cobertura_control1 { get; set; }
        public virtual a_campo_cobertura_control a_campo_cobertura_control2 { get; set; }
        public virtual a_campo_cobertura_control a_campo_cobertura_control3 { get; set; }
        public virtual a_campo_cobertura_control a_campo_cobertura_control4 { get; set; }
        public virtual a_campo_cobertura_control a_campo_cobertura_control5 { get; set; }
        public virtual a_campo_cobertura_control a_campo_cobertura_control6 { get; set; }
        public virtual a_campo_cobertura_control a_campo_cobertura_control7 { get; set; }
        public virtual a_campo_cobertura_control a_campo_cobertura_control8 { get; set; }
        public virtual a_campo_cobertura_control a_campo_cobertura_control9 { get; set; }
        public virtual a_campo_cobertura_control a_campo_cobertura_control10 { get; set; }
        public virtual a_campo_cobertura_control a_campo_cobertura_control11 { get; set; }
        public virtual a_campo_cobertura_control a_campo_cobertura_control12 { get; set; }
        public virtual a_campo_cobertura_control a_campo_cobertura_control13 { get; set; }
        public virtual k_control k_control { get; set; }
    }
}
