//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kd_r2811
    {
        public int idd_r2811 { get; set; }
        public int id_r2811 { get; set; }
        public string c01 { get; set; }
        public string c02 { get; set; }
        public string c03 { get; set; }
        public string c04 { get; set; }
        public string c05 { get; set; }
        public string c06 { get; set; }
        public string c07 { get; set; }
        public string c08 { get; set; }
        public string c09 { get; set; }
        public string c10 { get; set; }
        public string c11 { get; set; }
        public string c12 { get; set; }
        public string c13 { get; set; }
        public string c14 { get; set; }
        public string c15 { get; set; }
        public string c16 { get; set; }
        public string c17 { get; set; }
        public string c18 { get; set; }
        public string c19 { get; set; }
        public string c20 { get; set; }
        public string c21 { get; set; }
        public string c22 { get; set; }
        public string c23 { get; set; }
    
        public virtual kg_r2811 kg_r2811 { get; set; }
    }
}
