//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kg_r2811
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kg_r2811()
        {
            this.kd_r2811 = new HashSet<kd_r2811>();
        }
    
        public int id_r2811 { get; set; }
        public string anno { get; set; }
        public string mes { get; set; }
        public Nullable<System.DateTime> fe_generacion { get; set; }
        public string usr_generacion { get; set; }
        public int id_entidad { get; set; }
    
        public virtual c_entidad c_entidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kd_r2811> kd_r2811 { get; set; }
    }
}
