//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class r_control
    {
        public int id_registro_control { get; set; }
        public string actividad_control { get; set; }
        public string relacion_control { get; set; }
        public string evidencia_control { get; set; }
        public Nullable<int> id_ejecutor { get; set; }
        public Nullable<int> id_responsable { get; set; }
        public bool es_control_clave { get; set; }
        public Nullable<int> id_grado_cobertura { get; set; }
        public Nullable<int> id_frecuencia_control { get; set; }
        public Nullable<int> id_naturaleza_control { get; set; }
        public string nb_aplicacion { get; set; }
        public Nullable<int> id_tipologia_control { get; set; }
        public Nullable<int> id_categoria_control { get; set; }
        public Nullable<int> id_tipo_evidencia { get; set; }
        public bool tiene_accion_correctora { get; set; }
        public string accion_correctora { get; set; }
        public string ds_notificacion_incidencia { get; set; }
        public string campo01 { get; set; }
        public string campo02 { get; set; }
        public string campo03 { get; set; }
        public string campo04 { get; set; }
        public string campo05 { get; set; }
        public string campo06 { get; set; }
        public string campo07 { get; set; }
        public string campo08 { get; set; }
        public string campo09 { get; set; }
        public string campo10 { get; set; }
        public string campo11 { get; set; }
        public string campo12 { get; set; }
        public string campo13 { get; set; }
        public string campo14 { get; set; }
        public string campo15 { get; set; }
        public string campo16 { get; set; }
        public string campo17 { get; set; }
        public string campo18 { get; set; }
        public string campo19 { get; set; }
        public string campo20 { get; set; }
        public Nullable<int> id_control { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<System.DateTime> fe_modificacion { get; set; }
    
        public virtual c_categoria_control c_categoria_control { get; set; }
        public virtual c_frecuencia_control c_frecuencia_control { get; set; }
        public virtual c_grado_cobertura c_grado_cobertura { get; set; }
        public virtual c_naturaleza_control c_naturaleza_control { get; set; }
        public virtual c_tipo_evidencia c_tipo_evidencia { get; set; }
        public virtual c_tipologia_control c_tipologia_control { get; set; }
        public virtual c_usuario c_usuario { get; set; }
        public virtual c_usuario c_usuario1 { get; set; }
        public virtual c_usuario c_usuario2 { get; set; }
        public virtual k_control k_control { get; set; }
    }
}
