//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class r_macro_proceso
    {
        public int id_registro_macro_proceso { get; set; }
        public string nb_entidad { get; set; }
        public string cl_macro_proceso { get; set; }
        public string nb_macro_proceso { get; set; }
        public string nb_responsable { get; set; }
        public Nullable<int> id_macro_proceso { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<System.DateTime> fe_modificacion { get; set; }
    
        public virtual c_macro_proceso c_macro_proceso { get; set; }
        public virtual c_usuario c_usuario { get; set; }
    }
}
