//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using SCIRA.Properties;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class r_respuesta
    {
        public int id_respuesta { get; set; }
        public int id_incidencia { get; set; }
        public Nullable<System.DateTime> fe_solucion { get; set; }
        [Required(ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "Validacion001")]
        public string contestacion { get; set; }
        public string observaciones { get; set; }
        public string archivo_1 { get; set; }
        public string archivo_2 { get; set; }
        public string archivo_3 { get; set; }
    
        public virtual k_incidencia k_incidencia { get; set; }
    }
}
