//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class r_registro_evento
    {
        public int id_registro { get; set; }
        public int id_evento { get; set; }
        public System.DateTime fe_limite { get; set; }
        public bool terminado { get; set; }
    
        public virtual r_evento r_evento { get; set; }
    }
}
