//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class r_riesgo
    {
        public int id_registro_riesgo { get; set; }
        public string cl_riesgo { get; set; }
        public string nb_riesgo { get; set; }
        public string evento { get; set; }
        public Nullable<int> id_tipo_riesgo { get; set; }
        public Nullable<int> id_tipologia_riesgo { get; set; }
        public Nullable<int> id_probabilidad_ocurrencia { get; set; }
        public Nullable<int> id_tipo_impacto { get; set; }
        public Nullable<int> id_magnitud_impacto { get; set; }
        public string criticidad { get; set; }
        public bool tiene_afectacion_contable { get; set; }
        public string supuesto_normativo { get; set; }
        public string euc { get; set; }
        public string campo01 { get; set; }
        public string campo02 { get; set; }
        public string campo03 { get; set; }
        public string campo04 { get; set; }
        public string campo05 { get; set; }
        public string campo06 { get; set; }
        public string campo07 { get; set; }
        public string campo08 { get; set; }
        public string campo09 { get; set; }
        public string campo10 { get; set; }
        public string campo11 { get; set; }
        public string campo12 { get; set; }
        public string campo13 { get; set; }
        public string campo14 { get; set; }
        public string campo15 { get; set; }
        public string campo16 { get; set; }
        public string campo17 { get; set; }
        public string campo18 { get; set; }
        public string campo19 { get; set; }
        public string campo20 { get; set; }
        public Nullable<int> id_riesgo { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<System.DateTime> fe_modificacion { get; set; }
    
        public virtual c_magnitud_impacto c_magnitud_impacto { get; set; }
        public virtual c_probabilidad_ocurrencia c_probabilidad_ocurrencia { get; set; }
        public virtual c_tipo_impacto c_tipo_impacto { get; set; }
        public virtual c_tipo_riesgo c_tipo_riesgo { get; set; }
        public virtual c_tipologia_riesgo c_tipologia_riesgo { get; set; }
        public virtual c_usuario c_usuario { get; set; }
        public virtual k_riesgo k_riesgo { get; set; }
    }
}
