//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class r_sub_proceso
    {
        public int id_registro_sub_proceso { get; set; }
        public string nb_entidad { get; set; }
        public string nb_macro_proceso { get; set; }
        public string nb_proceso { get; set; }
        public string cl_sub_proceso { get; set; }
        public string nb_sub_proceso { get; set; }
        public string ds_sub_proceso { get; set; }
        public string nb_responsable { get; set; }
        public string participantes { get; set; }
        public int no_meses_antiguedad { get; set; }
        public string cl_manual { get; set; }
        public string cl_sp_anterior { get; set; }
        public string cl_sp_siguiente { get; set; }
        public string tipologia_sub_proceso { get; set; }
        public string nb_etapa { get; set; }
        public string nb_sub_etapa { get; set; }
        public string ds_areas_involucradas { get; set; }
        public string ds_aplicaciones_relacionadas { get; set; }
        public string nb_archivo_manual { get; set; }
        public string nb_archivo_flujo { get; set; }
        public string lineas_negocio { get; set; }
        public string areas_costeo { get; set; }
        public string campo01 { get; set; }
        public string campo02 { get; set; }
        public string campo03 { get; set; }
        public string campo04 { get; set; }
        public string campo05 { get; set; }
        public string campo06 { get; set; }
        public string campo07 { get; set; }
        public string campo08 { get; set; }
        public string campo09 { get; set; }
        public string campo10 { get; set; }
        public string campo11 { get; set; }
        public string campo12 { get; set; }
        public string campo13 { get; set; }
        public string campo14 { get; set; }
        public string campo15 { get; set; }
        public string campo16 { get; set; }
        public string campo17 { get; set; }
        public string campo18 { get; set; }
        public string campo19 { get; set; }
        public string campo20 { get; set; }
        public Nullable<int> id_sub_proceso { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<System.DateTime> fe_modificacion { get; set; }
    
        public virtual c_sub_proceso c_sub_proceso { get; set; }
        public virtual c_usuario c_usuario { get; set; }
    }
}
