//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_bdei
    {
        public long ID { get; set; }
        public string nb_entidad { get; set; }
        public string nb_estatus_bdei { get; set; }
        public string nb_sub_proceso { get; set; }
        public string nb_usuario_sub_proceso { get; set; }
        public string nb_usuario_captura { get; set; }
        public string id_criticidad_riesgo_ro { get; set; }
        public string nb_tipo_ro { get; set; }
        public string nb_clase_evento { get; set; }
        public string nb_ambito_ro { get; set; }
        public string nb_proceso_ro { get; set; }
        public string nb_producto_ro { get; set; }
        public string nb_sub_tipo_producto_ro { get; set; }
        public string nb_canal_ro { get; set; }
        public string nb_categoria_linea_negocio_ro { get; set; }
        public string nb_linea_negocio_ro { get; set; }
        public string nb_frecuencia_ro { get; set; }
        public string nb_impacto_ro { get; set; }
        public string nb_criticidad_ro { get; set; }
        public Nullable<System.DateTime> fe_alta { get; set; }
        public Nullable<System.DateTime> fe_ocurrencia { get; set; }
        public string hr_ocurrencia { get; set; }
        public Nullable<short> duracion { get; set; }
        public Nullable<System.DateTime> fe_solucion { get; set; }
        public string nb_tipo_solucion { get; set; }
        public string comentarios { get; set; }
        public string nb_moneda { get; set; }
        public string cl_cuenta_contable_perdida { get; set; }
        public string nb_cuenta_contable_perdida { get; set; }
        public Nullable<decimal> mn_exposicion { get; set; }
        public Nullable<decimal> mn_quebranto { get; set; }
        public string cl_centro_costo { get; set; }
        public string nb_centro_costo { get; set; }
        public Nullable<System.DateTime> fe_registro_perdida { get; set; }
        public Nullable<System.DateTime> fe_quebranto { get; set; }
        public Nullable<decimal> mn_recuperacion { get; set; }
        public string nb_usuario_recuperacion { get; set; }
        public string cl_cuenta_contable_recuperacion { get; set; }
        public string nb_cuenta_contable_recuperacion { get; set; }
        public Nullable<System.DateTime> fe_registro_recuperacion { get; set; }
        public string via_recuperacion { get; set; }
        public Nullable<decimal> mn_costo_recuperacion { get; set; }
        public string cl_cuenta_contable_costo { get; set; }
        public string nb_cuenta_contable_costo { get; set; }
        public Nullable<System.DateTime> fe_registro_costo_recuperacion { get; set; }
    }
}
