//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_certificacion
    {
        public long ID { get; set; }
        public string cnb_entidad { get; set; }
        public string cnb_macro_proceso { get; set; }
        public string cnb_proceso { get; set; }
        public string cnb_sub_proceso { get; set; }
        public string codigo_riesgo { get; set; }
        public string evento { get; set; }
        public string codigo_control { get; set; }
        public string actividad_control { get; set; }
        public bool tiene_accion_correctora { get; set; }
        public string accion_correctora { get; set; }
        public string cl_certificacion_control { get; set; }
        public string nb_periodo_certificacion { get; set; }
        public string ds_procedimiento_certificacion { get; set; }
        public string nb_tipo_evaluacion { get; set; }
        public Nullable<short> no_partidas_minimo { get; set; }
        public Nullable<short> no_partidas_semestre1 { get; set; }
        public Nullable<short> no_partidas_semestre2 { get; set; }
        public short no_pruebas_realizadas { get; set; }
        public bool tiene_funcionamiento_efectivo { get; set; }
        public bool tiene_disenio_efectivo { get; set; }
        public string ds_plan_remediacion { get; set; }
        public System.DateTime fe_registro { get; set; }
        public string nb_archivo_1 { get; set; }
        public string nb_archivo_2 { get; set; }
        public string nb_archivo_3 { get; set; }
        public string nb_archivo_4 { get; set; }
        public string nb_archivo_5 { get; set; }
    }
}
