//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_estructura
    {
        public long ID { get; set; }
        public string cl_entidad { get; set; }
        public string nb_entidad { get; set; }
        public string nb_responsable_entidad { get; set; }
        public string nb_puesto_entidad { get; set; }
        public string cl_macro_proceso { get; set; }
        public string nb_macro_proceso { get; set; }
        public string nb_responsable_macro_proceso { get; set; }
        public string nb_puesto_macro_proceso { get; set; }
        public string cl_proceso { get; set; }
        public string nb_proceso { get; set; }
        public string nb_responsbale_proceso { get; set; }
        public string nb_puesto_proceso { get; set; }
        public string cl_sub_proceso { get; set; }
        public string nb_sub_proceso { get; set; }
        public string cl_manual { get; set; }
        public string nb_responsable_sub_proceso { get; set; }
        public string nb_puesto_sub_proceso { get; set; }
    }
}
