//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_indicador
    {
        public long ID { get; set; }
        public string nb_entidad { get; set; }
        public string cl_indicador { get; set; }
        public string nb_indicador { get; set; }
        public string ds_indicador { get; set; }
        public string ds_numerador { get; set; }
        public string ds_denominador { get; set; }
        public string nb_frecuencia_indicador { get; set; }
        public string nb_unidad_indicador { get; set; }
        public string control_asociado { get; set; }
        public decimal peso { get; set; }
        public decimal umbral000i { get; set; }
        public decimal umbral000f { get; set; }
        public decimal umbral050i { get; set; }
        public decimal umbral050f { get; set; }
        public decimal umbral075i { get; set; }
        public decimal umbral075f { get; set; }
        public decimal umbral100i { get; set; }
        public decimal umbral100f { get; set; }
        public bool esta_activo { get; set; }
        public string nb_area { get; set; }
        public string nb_responsable { get; set; }
        public string nb_periodo_indicador { get; set; }
        public decimal numerador { get; set; }
        public decimal denominador { get; set; }
        public decimal medicion { get; set; }
        public string nb_calificacion_indicador { get; set; }
    }
}
