//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_IyP_t4
    {
        public long ID { get; set; }
        public string ruta_control { get; set; }
        public string codigo_control { get; set; }
        public string cl_certificacion_control { get; set; }
        public string periodo_certificacion { get; set; }
        public string ds_procedimiento_certificacion { get; set; }
        public string lvl_1 { get; set; }
        public string lvl_2 { get; set; }
        public string lvl_3 { get; set; }
        public string lvl_4 { get; set; }
        public string lvl_5 { get; set; }
        public int id_incidencia { get; set; }
        public string ds_incidencia { get; set; }
        public string nb_resp_inc { get; set; }
        public string cnb_clasificacion_incidencia { get; set; }
        public bool requiere_plan { get; set; }
        public Nullable<int> id_plan { get; set; }
        public string nb_plan { get; set; }
        public string ds_plan { get; set; }
        public string cnb_area { get; set; }
        public string nb_resp_plan { get; set; }
        public string nb_resp_seguimiento { get; set; }
        public Nullable<System.DateTime> fe_alta_p { get; set; }
        public Nullable<System.DateTime> fe_estimada_implantacion { get; set; }
        public Nullable<System.DateTime> fe_real_solucion { get; set; }
        public Nullable<System.DateTime> fe_seguimiento { get; set; }
        public string obs_seguimiento { get; set; }
    }
}
