//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCIRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_mryc
    {
        public long ID { get; set; }
        public string cl_entidad { get; set; }
        public string nb_entidad { get; set; }
        public string nb_responsable_entidad { get; set; }
        public string nb_puesto_entidad { get; set; }
        public string cl_macro_proceso { get; set; }
        public string nb_macro_proceso { get; set; }
        public string nb_responsable_macro_proceso { get; set; }
        public string nb_puesto_macro_proceso { get; set; }
        public string cl_proceso { get; set; }
        public string nb_proceso { get; set; }
        public string nb_responsable_proceso { get; set; }
        public string nb_puesto_proceso { get; set; }
        public Nullable<int> id_sub_proceso { get; set; }
        public string cl_sub_proceso { get; set; }
        public string nb_sub_proceso { get; set; }
        public string cl_manual { get; set; }
        public string nb_responsable_sub_proceso { get; set; }
        public string nb_puesto_sub_proceso { get; set; }
        public string nb_etapa { get; set; }
        public string nb_sub_etapa { get; set; }
        public string ds_areas_involucradas { get; set; }
        public string ds_aplicaciones_relacionadas { get; set; }
        public string cl_riesgo { get; set; }
        public string nb_riesgo { get; set; }
        public string evento { get; set; }
        public string nb_tipo_riesgo { get; set; }
        public string nb_categoria_riesgo { get; set; }
        public string nb_clase_tipologia_riesgo { get; set; }
        public string nb_sub_clase_tipologia_riesgo { get; set; }
        public string nb_tipologia_riesgo { get; set; }
        public string criticidad { get; set; }
        public Nullable<bool> tiene_afectacion_contable { get; set; }
        public string supuesto_normativo { get; set; }
        public string euc { get; set; }
        public string nb_tipo_impacto { get; set; }
        public string nb_magnitud_impacto { get; set; }
        public string nb_probabilidad_ocurrencia { get; set; }
        public string relacion_control { get; set; }
        public string actividad_control { get; set; }
        public string evidencia_control { get; set; }
        public Nullable<bool> es_control_clave { get; set; }
        public string nb_aplicacion { get; set; }
        public string accion_correctora { get; set; }
        public string nb_naturaleza_control { get; set; }
        public string nb_frecuencia_control { get; set; }
        public string nb_categoria_control { get; set; }
        public string nb_tipologia_control { get; set; }
        public string nb_tipo_evidencia { get; set; }
        public string nb_grado_cobertura { get; set; }
        public string nb_responsable_control { get; set; }
        public string nb_ejecutor_control { get; set; }
        public string campo01 { get; set; }
        public string campo02 { get; set; }
        public string campo03 { get; set; }
        public string campo04 { get; set; }
        public string campo05 { get; set; }
        public string campo06 { get; set; }
        public string campo07 { get; set; }
        public string campo08 { get; set; }
        public string campo09 { get; set; }
        public string campo10 { get; set; }
        public string campo11 { get; set; }
        public string campo12 { get; set; }
        public string campo13 { get; set; }
        public string campo14 { get; set; }
        public string campo15 { get; set; }
        public string campo16 { get; set; }
        public string campo17 { get; set; }
        public string campo18 { get; set; }
        public string campo19 { get; set; }
        public string campo20 { get; set; }
        public string campor01 { get; set; }
        public string campor02 { get; set; }
        public string campor03 { get; set; }
        public string campor04 { get; set; }
        public string campor05 { get; set; }
        public string campor06 { get; set; }
        public string campor07 { get; set; }
        public string campor08 { get; set; }
        public string campor09 { get; set; }
        public string campor10 { get; set; }
        public string campor11 { get; set; }
        public string campor12 { get; set; }
        public string campor13 { get; set; }
        public string campor14 { get; set; }
        public string campor15 { get; set; }
        public string campor16 { get; set; }
        public string campor17 { get; set; }
        public string campor18 { get; set; }
        public string campor19 { get; set; }
        public string campor20 { get; set; }
        public string camposp01 { get; set; }
        public string camposp02 { get; set; }
        public string camposp03 { get; set; }
        public string camposp04 { get; set; }
        public string camposp05 { get; set; }
        public string camposp06 { get; set; }
        public string camposp07 { get; set; }
        public string camposp08 { get; set; }
        public string camposp09 { get; set; }
        public string camposp10 { get; set; }
        public string camposp11 { get; set; }
        public string camposp12 { get; set; }
        public string camposp13 { get; set; }
        public string camposp14 { get; set; }
        public string camposp15 { get; set; }
        public string camposp16 { get; set; }
        public string camposp17 { get; set; }
        public string camposp18 { get; set; }
        public string camposp19 { get; set; }
        public string camposp20 { get; set; }
    }
}
